#cloud-config
# configuracion de usuarios
#
users:
  - name: adminunir
    gecos: adminunir created user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-rsa 
